version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: hkcrm2-postgres
    environment:
      POSTGRES_DB: HK-CRM-BD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 314151
    ports:
      - "5554:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
